# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-04 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='riskdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', models.CharField(blank=True, max_length=50, null=True)),
                ('riskdesc', models.CharField(blank=True, max_length=50, null=True)),
                ('risksol', models.CharField(blank=True, max_length=50, null=True)),
                ('consequence', models.IntegerField(null=True)),
                ('likelihood', models.IntegerField(null=True)),
            ],
        ),
    ]
